<a href="https://colab.research.google.com/github/Sulthana-2000/Machine-Learning-Classification-Models/blob/main/Naive_Bayes(Credit_Score).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
df=pd.read_csv('/content/Credit Score Classification Dataset (1).csv')
df

,Age,Gender,Income,Education,Marital Status,Number of Children,Home Ownership,Credit Score
0,25,Female,50000.0,Bachelor's Degree,Single,0,Rented,High
1,30,Male,100000.0,Master's Degree,Married,2,Owned,High
2,35,Female,75000.0,Doctorate,Married,1,Owned,High
3,40,Male,125000.0,High School Diploma,Single,0,Owned,High
4,45,Female,100000.0,Bachelor's Degree,Married,3,Owned,High
...,...,...,...,...,...,...,...,...
159,29,Female,27500.0,High School Diploma,Single,0,Rented,Low
160,34,Male,47500.0,Associate's Degree,Single,0,Rented,Average
161,39,Female,62500.0,Bachelor's Degree,Married,2,Owned,High
162,44,Male,87500.0,Master's Degree,Single,0,Owned,High
163,49,Female,77500.0,Doctorate,Married,1,Owned,High

In [2]:
df.head()

,Age,Gender,Income,Education,Marital Status,Number of Children,Home Ownership,Credit Score
0,25,Female,50000.0,Bachelor's Degree,Single,0,Rented,High
1,30,Male,100000.0,Master's Degree,Married,2,Owned,High
2,35,Female,75000.0,Doctorate,Married,1,Owned,High
3,40,Male,125000.0,High School Diploma,Single,0,Owned,High
4,45,Female,100000.0,Bachelor's Degree,Married,3,Owned,High

In [3]:
df.tail()

,Age,Gender,Income,Education,Marital Status,Number of Children,Home Ownership,Credit Score
159,29,Female,27500.0,High School Diploma,Single,0,Rented,Low
160,34,Male,47500.0,Associate's Degree,Single,0,Rented,Average
161,39,Female,62500.0,Bachelor's Degree,Married,2,Owned,High
162,44,Male,87500.0,Master's Degree,Single,0,Owned,High
163,49,Female,77500.0,Doctorate,Married,1,Owned,High

In [4]:
df.dtypes

Age                     int64
Gender                 object
Income                float64
Education              object
Marital Status         object
Number of Children      int64
Home Ownership         object
Credit Score           object
dtype: object

In [5]:
df.isna().sum()

Age                   0
Gender                6
Income                9
Education             0
Marital Status        0
Number of Children    0
Home Ownership        0
Credit Score          0
dtype: int64

In [6]:
# to fill the objects we use mode
a=df['Gender'].mode()[0]
df['Gender'].fillna(a,inplace=True)

b=df['Income'].mean()
df['Income'].fillna(b,inplace=True)
df.isna().sum()

Age                   0
Gender                0
Income                0
Education             0
Marital Status        0
Number of Children    0
Home Ownership        0
Credit Score          0
dtype: int64

In [7]:
from sklearn.preprocessing import LabelEncoder
lab=LabelEncoder()
df['Gender']=lab.fit_transform(df['Gender'])
df['Gender']

0      0
1      1
2      0
3      1
4      0
      ..
159    0
160    1
161    0
162    1
163    0
Name: Gender, Length: 164, dtype: int64

In [8]:
df['Education']=lab.fit_transform(df['Education'])
df['Education']

0      1
1      4
2      2
3      3
4      1
      ..
159    3
160    0
161    1
162    4
163    2
Name: Education, Length: 164, dtype: int64

In [9]:
df['Marital Status']=lab.fit_transform(df['Marital Status'])
df['Marital Status']

0      1
1      0
2      0
3      1
4      0
      ..
159    1
160    1
161    0
162    1
163    0
Name: Marital Status, Length: 164, dtype: int64

In [10]:
df['Home Ownership']=lab.fit_transform(df['Home Ownership'])
df['Home Ownership']

0      1
1      0
2      0
3      0
4      0
      ..
159    1
160    1
161    0
162    0
163    0
Name: Home Ownership, Length: 164, dtype: int64

In [11]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)
x_train

array([[4.50000000e+01, 0.00000000e+00, 1.15000000e+05, 1.00000000e+00,
        0.00000000e+00, 3.00000000e+00, 0.00000000e+00],
       [5.10000000e+01, 1.00000000e+00, 1.35000000e+05, 1.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.50000000e+01, 0.00000000e+00, 1.10000000e+05, 1.00000000e+00,
        0.00000000e+00, 3.00000000e+00, 0.00000000e+00],
       [3.40000000e+01, 1.00000000e+00, 4.75000000e+04, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [2.60000000e+01, 0.00000000e+00, 4.00000000e+04, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [4.40000000e+01, 1.00000000e+00, 7.50000000e+04, 4.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.20000000e+01, 1.00000000e+00, 1.05000000e+05, 4.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.10000000e+01, 1.00000000e+00, 6.50000000e+04, 1.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [4.10000000e+01, 1.00000000e+00, 1.10000000e+05, 2.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.70000000e+01, 0.00000000e+00, 3.75000000e+04, 3.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [4.50000000e+01, 0.00000000e+00, 1.00000000e+05, 1.00000000e+00,
        0.00000000e+00, 3.00000000e+00, 0.00000000e+00],
       [4.00000000e+01, 1.00000000e+00, 1.30000000e+05, 3.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.00000000e+01, 1.00000000e+00, 1.30000000e+05, 3.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.10000000e+01, 1.00000000e+00, 1.10000000e+05, 2.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.70000000e+01, 0.00000000e+00, 8.39516129e+04, 2.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [3.10000000e+01, 1.00000000e+00, 6.75000000e+04, 1.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [4.60000000e+01, 0.00000000e+00, 9.00000000e+04, 3.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [4.00000000e+01, 1.00000000e+00, 1.42500000e+05, 3.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.80000000e+01, 0.00000000e+00, 8.39516129e+04, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [2.50000000e+01, 0.00000000e+00, 5.00000000e+04, 1.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [2.50000000e+01, 0.00000000e+00, 5.75000000e+04, 1.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [3.00000000e+01, 1.00000000e+00, 1.12500000e+05, 4.00000000e+00,
        0.00000000e+00, 2.00000000e+00, 0.00000000e+00],
       [4.00000000e+01, 1.00000000e+00, 1.42500000e+05, 3.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.20000000e+01, 1.00000000e+00, 1.00000000e+05, 4.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [5.10000000e+01, 1.00000000e+00, 1.40000000e+05, 1.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.90000000e+01, 0.00000000e+00, 6.50000000e+04, 2.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [5.10000000e+01, 1.00000000e+00, 1.40000000e+05, 1.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.30000000e+01, 1.00000000e+00, 8.39516129e+04, 4.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.40000000e+01, 1.00000000e+00, 4.50000000e+04, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [5.30000000e+01, 1.00000000e+00, 1.15000000e+05, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.90000000e+01, 0.00000000e+00, 6.25000000e+04, 1.00000000e+00,
        0.00000000e+00, 2.00000000e+00, 0.00000000e+00],
       [3.80000000e+01, 0.00000000e+00, 6.75000000e+04, 1.00000000e+00,
        0.00000000e+00, 2.00000000e+00, 0.00000000e+00],
       [2.80000000e+01, 0.00000000e+00, 3.25000000e+04, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [4.60000000e+01, 0.00000000e+00, 9.50000000e+04, 3.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [2.50000000e+01, 0.00000000e+00, 5.75000000e+04, 1.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [4.20000000e+01, 1.00000000e+00, 1.10000000e+05, 4.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.90000000e+01, 0.00000000e+00, 2.75000000e+04, 3.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [3.50000000e+01, 0.00000000e+00, 8.00000000e+04, 2.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [2.80000000e+01, 0.00000000e+00, 3.25000000e+04, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [3.50000000e+01, 0.00000000e+00, 8.50000000e+04, 2.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [2.50000000e+01, 0.00000000e+00, 6.00000000e+04, 1.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [2.70000000e+01, 0.00000000e+00, 3.75000000e+04, 3.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [4.50000000e+01, 0.00000000e+00, 1.05000000e+05, 1.00000000e+00,
        0.00000000e+00, 3.00000000e+00, 0.00000000e+00],
       [3.30000000e+01, 1.00000000e+00, 8.39516129e+04, 3.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [4.40000000e+01, 1.00000000e+00, 8.75000000e+04, 4.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.80000000e+01, 1.00000000e+00, 7.50000000e+04, 1.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [3.00000000e+01, 1.00000000e+00, 1.17500000e+05, 4.00000000e+00,
        0.00000000e+00, 2.00000000e+00, 0.00000000e+00],
       [4.40000000e+01, 1.00000000e+00, 8.75000000e+04, 4.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.10000000e+01, 1.00000000e+00, 7.00000000e+04, 1.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [5.10000000e+01, 1.00000000e+00, 1.50000000e+05, 1.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.90000000e+01, 0.00000000e+00, 2.75000000e+04, 3.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [5.00000000e+01, 1.00000000e+00, 1.50000000e+05, 4.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.40000000e+01, 1.00000000e+00, 4.75000000e+04, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [3.50000000e+01, 0.00000000e+00, 9.00000000e+04, 2.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [4.70000000e+01, 0.00000000e+00, 9.00000000e+04, 2.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [3.80000000e+01, 0.00000000e+00, 6.75000000e+04, 1.00000000e+00,
        0.00000000e+00, 2.00000000e+00, 0.00000000e+00],
       [2.60000000e+01, 0.00000000e+00, 4.50000000e+04, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [3.30000000e+01, 1.00000000e+00, 5.25000000e+04, 3.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [4.70000000e+01, 0.00000000e+00, 9.50000000e+04, 2.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [5.00000000e+01, 1.00000000e+00, 1.55000000e+05, 4.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [5.20000000e+01, 1.00000000e+00, 1.30000000e+05, 3.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.10000000e+01, 1.00000000e+00, 6.00000000e+04, 1.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [3.70000000e+01, 0.00000000e+00, 7.25000000e+04, 1.00000000e+00,
        0.00000000e+00, 2.00000000e+00, 0.00000000e+00],
       [4.10000000e+01, 1.00000000e+00, 1.15000000e+05, 2.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.50000000e+01, 0.00000000e+00, 6.00000000e+04, 1.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [5.20000000e+01, 1.00000000e+00, 8.39516129e+04, 3.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.00000000e+01, 1.00000000e+00, 1.12500000e+05, 4.00000000e+00,
        0.00000000e+00, 2.00000000e+00, 0.00000000e+00],
       [4.80000000e+01, 0.00000000e+00, 8.50000000e+04, 2.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [2.70000000e+01, 0.00000000e+00, 3.75000000e+04, 3.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [3.20000000e+01, 1.00000000e+00, 5.75000000e+04, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [4.90000000e+01, 0.00000000e+00, 7.75000000e+04, 2.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [3.60000000e+01, 0.00000000e+00, 8.00000000e+04, 4.00000000e+00,
        0.00000000e+00, 2.00000000e+00, 0.00000000e+00],
       [4.30000000e+01, 1.00000000e+00, 9.25000000e+04, 4.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.80000000e+01, 0.00000000e+00, 8.39516129e+04, 1.00000000e+00,
        0.00000000e+00, 2.00000000e+00, 0.00000000e+00],
       [3.20000000e+01, 1.00000000e+00, 5.50000000e+04, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [3.00000000e+01, 1.00000000e+00, 1.12500000e+05, 4.00000000e+00,
        0.00000000e+00, 2.00000000e+00, 0.00000000e+00],
       [5.00000000e+01, 1.00000000e+00, 1.55000000e+05, 4.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.00000000e+01, 1.00000000e+00, 1.25000000e+05, 3.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [5.20000000e+01, 1.00000000e+00, 1.25000000e+05, 3.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [5.10000000e+01, 1.00000000e+00, 1.45000000e+05, 1.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.60000000e+01, 0.00000000e+00, 8.50000000e+04, 4.00000000e+00,
        0.00000000e+00, 2.00000000e+00, 0.00000000e+00],
       [3.00000000e+01, 1.00000000e+00, 1.05000000e+05, 4.00000000e+00,
        0.00000000e+00, 2.00000000e+00, 0.00000000e+00],
       [4.20000000e+01, 0.00000000e+00, 1.00000000e+05, 4.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.50000000e+01, 0.00000000e+00, 9.00000000e+04, 2.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [3.40000000e+01, 1.00000000e+00, 4.75000000e+04, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [3.70000000e+01, 0.00000000e+00, 7.75000000e+04, 1.00000000e+00,
        0.00000000e+00, 2.00000000e+00, 0.00000000e+00],
       [4.30000000e+01, 1.00000000e+00, 9.25000000e+04, 4.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.90000000e+01, 0.00000000e+00, 6.25000000e+04, 1.00000000e+00,
        0.00000000e+00, 2.00000000e+00, 0.00000000e+00],
       [2.50000000e+01, 0.00000000e+00, 5.75000000e+04, 1.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [3.30000000e+01, 1.00000000e+00, 5.25000000e+04, 3.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [4.40000000e+01, 1.00000000e+00, 8.75000000e+04, 4.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.30000000e+01, 1.00000000e+00, 8.00000000e+04, 4.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.90000000e+01, 0.00000000e+00, 7.75000000e+04, 2.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [5.30000000e+01, 1.00000000e+00, 1.22500000e+05, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.30000000e+01, 0.00000000e+00, 8.20000000e+04, 4.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [3.60000000e+01, 0.00000000e+00, 8.50000000e+04, 4.00000000e+00,
        0.00000000e+00, 2.00000000e+00, 0.00000000e+00],
       [3.30000000e+01, 0.00000000e+00, 5.25000000e+04, 3.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [3.00000000e+01, 1.00000000e+00, 1.00000000e+05, 4.00000000e+00,
        0.00000000e+00, 2.00000000e+00, 0.00000000e+00],
       [5.30000000e+01, 1.00000000e+00, 1.22500000e+05, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.70000000e+01, 0.00000000e+00, 7.25000000e+04, 1.00000000e+00,
        0.00000000e+00, 2.00000000e+00, 0.00000000e+00],
       [3.10000000e+01, 1.00000000e+00, 9.50000000e+04, 2.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [4.60000000e+01, 0.00000000e+00, 1.02500000e+05, 3.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [2.60000000e+01, 0.00000000e+00, 5.00000000e+04, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [5.30000000e+01, 1.00000000e+00, 8.39516129e+04, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.90000000e+01, 0.00000000e+00, 6.25000000e+04, 1.00000000e+00,
        0.00000000e+00, 2.00000000e+00, 0.00000000e+00],
       [3.20000000e+01, 1.00000000e+00, 5.75000000e+04, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [4.90000000e+01, 0.00000000e+00, 7.75000000e+04, 2.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [4.90000000e+01, 0.00000000e+00, 7.75000000e+04, 2.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [3.80000000e+01, 0.00000000e+00, 6.50000000e+04, 1.00000000e+00,
        0.00000000e+00, 2.00000000e+00, 0.00000000e+00],
       [4.60000000e+01, 0.00000000e+00, 9.75000000e+04, 3.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [3.20000000e+01, 1.00000000e+00, 5.75000000e+04, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [3.70000000e+01, 0.00000000e+00, 7.00000000e+04, 1.00000000e+00,
        0.00000000e+00, 2.00000000e+00, 0.00000000e+00],
       [3.50000000e+01, 0.00000000e+00, 8.50000000e+04, 2.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [4.10000000e+01, 1.00000000e+00, 1.20000000e+05, 2.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [19]:
y_train

array(['High', 'High', 'High', 'Average', 'Average', 'High', 'High',
       'Average', 'High', 'Low', 'High', 'High', 'High', 'High', 'High',
       'Average', 'High', 'High', 'Low', 'High', 'Average', 'High',
       'High', 'High', 'High', 'High', 'High', 'High', 'Average', 'High',
       'High', 'High', 'Low', 'High', 'Average', 'High', 'Low', 'High',
       'Low', 'High', 'Average', 'Low', 'High', 'Average', 'High',
       'Average', 'High', 'High', 'Average', 'High', 'Low', 'High',
       'Average', 'High', 'High', 'High', 'Average', 'Average', 'High',
       'High', 'High', 'Average', 'High', 'High', 'Average', 'High',
       'High', 'High', 'Low', 'Average', 'High', 'High', 'High', 'High',
       'Average', 'High', 'High', 'High', 'High', 'High', 'High', 'High',
       'High', 'High', 'Average', 'High', 'High', 'High', 'Average',
       'Average', 'High', 'High', 'High', 'High', 'High', 'High',
       'Average', 'High', 'High', 'High', 'High', 'High', 'Average',
       'High', 'High', 'Average', 'High', 'High', 'High', 'High',
       'Average', 'High', 'High', 'High'], dtype=object)

In [21]:
x_test

array([[2.50000000e+01, 0.00000000e+00, 5.50000000e+04, 1.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [4.80000000e+01, 0.00000000e+00, 8.39516129e+04, 2.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [2.60000000e+01, 0.00000000e+00, 5.50000000e+04, 1.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [3.90000000e+01, 0.00000000e+00, 6.25000000e+04, 1.00000000e+00,
        0.00000000e+00, 2.00000000e+00, 0.00000000e+00],
       [3.50000000e+01, 0.00000000e+00, 9.00000000e+04, 2.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [2.50000000e+01, 0.00000000e+00, 5.50000000e+04, 1.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [4.80000000e+01, 0.00000000e+00, 8.25000000e+04, 2.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [4.80000000e+01, 0.00000000e+00, 8.25000000e+04, 2.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [3.60000000e+01, 0.00000000e+00, 9.50000000e+04, 4.00000000e+00,
        0.00000000e+00, 2.00000000e+00, 0.00000000e+00],
       [4.60000000e+01, 0.00000000e+00, 9.50000000e+04, 3.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [3.30000000e+01, 1.00000000e+00, 5.00000000e+04, 3.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [2.90000000e+01, 0.00000000e+00, 2.75000000e+04, 3.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [4.20000000e+01, 1.00000000e+00, 9.50000000e+04, 4.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [5.00000000e+01, 1.00000000e+00, 1.60000000e+05, 4.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.90000000e+01, 0.00000000e+00, 2.50000000e+04, 3.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [3.00000000e+01, 1.00000000e+00, 1.05000000e+05, 4.00000000e+00,
        0.00000000e+00, 2.00000000e+00, 0.00000000e+00],
       [3.20000000e+01, 1.00000000e+00, 8.50000000e+04, 4.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [2.70000000e+01, 0.00000000e+00, 3.75000000e+04, 3.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [5.20000000e+01, 0.00000000e+00, 1.30000000e+05, 3.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.70000000e+01, 0.00000000e+00, 8.50000000e+04, 2.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [3.70000000e+01, 0.00000000e+00, 7.50000000e+04, 1.00000000e+00,
        0.00000000e+00, 2.00000000e+00, 0.00000000e+00],
       [2.80000000e+01, 0.00000000e+00, 3.00000000e+04, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [2.70000000e+01, 0.00000000e+00, 3.50000000e+04, 3.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [4.10000000e+01, 1.00000000e+00, 1.05000000e+05, 2.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.50000000e+01, 0.00000000e+00, 8.00000000e+04, 2.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [3.80000000e+01, 0.00000000e+00, 6.75000000e+04, 1.00000000e+00,
        0.00000000e+00, 2.00000000e+00, 0.00000000e+00],
       [5.00000000e+01, 1.00000000e+00, 1.62500000e+05, 4.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.40000000e+01, 1.00000000e+00, 8.75000000e+04, 4.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.40000000e+01, 1.00000000e+00, 1.05000000e+05, 1.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [3.40000000e+01, 1.00000000e+00, 4.75000000e+04, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [4.50000000e+01, 0.00000000e+00, 1.05000000e+05, 1.00000000e+00,
        0.00000000e+00, 3.00000000e+00, 0.00000000e+00],
       [5.20000000e+01, 1.00000000e+00, 1.35000000e+05, 3.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.50000000e+01, 0.00000000e+00, 8.50000000e+04, 2.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [5.30000000e+01, 1.00000000e+00, 1.25000000e+05, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.50000000e+01, 0.00000000e+00, 7.50000000e+04, 2.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [3.00000000e+01, 1.00000000e+00, 1.17500000e+05, 4.00000000e+00,
        0.00000000e+00, 2.00000000e+00, 0.00000000e+00],
       [4.70000000e+01, 0.00000000e+00, 9.00000000e+04, 2.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [3.20000000e+01, 1.00000000e+00, 5.75000000e+04, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [3.60000000e+01, 0.00000000e+00, 9.00000000e+04, 4.00000000e+00,
        0.00000000e+00, 2.00000000e+00, 0.00000000e+00],
       [2.80000000e+01, 0.00000000e+00, 3.25000000e+04, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [3.90000000e+01, 0.00000000e+00, 6.00000000e+04, 1.00000000e+00,
        0.00000000e+00, 2.00000000e+00, 0.00000000e+00],
       [2.60000000e+01, 0.00000000e+00, 4.50000000e+04, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [2.90000000e+01, 0.00000000e+00, 8.39516129e+04, 3.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [2.50000000e+01, 0.00000000e+00, 6.25000000e+04, 1.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [2.90000000e+01, 0.00000000e+00, 6.80000000e+04, 2.00000000e+00,
        0.00000000e+00, 2.00000000e+00, 0.00000000e+00],
       [3.10000000e+01, 1.00000000e+00, 6.50000000e+04, 1.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [4.30000000e+01, 1.00000000e+00, 9.25000000e+04, 4.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.80000000e+01, 0.00000000e+00, 7.00000000e+04, 2.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [3.00000000e+01, 1.00000000e+00, 1.17500000e+05, 4.00000000e+00,
        0.00000000e+00, 2.00000000e+00, 0.00000000e+00],
       [2.60000000e+01, 0.00000000e+00, 4.75000000e+04, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

In [13]:
y_test

array(['Average', 'High', 'Average', 'High', 'High', 'Average', 'High',
       'High', 'High', 'High', 'Average', 'Low', 'High', 'High', 'Low',
       'High', 'High', 'Low', 'High', 'High', 'High', 'Low', 'Low',
       'High', 'High', 'High', 'High', 'High', 'High', 'Average', 'High',
       'High', 'High', 'High', 'High', 'High', 'High', 'Average', 'High',
       'Low', 'High', 'Average', 'Low', 'Average', 'Average', 'Average',
       'High', 'High', 'High', 'Average'], dtype=object)

In [14]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)

In [18]:
# Model Creation
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

array(['Average', 'High', 'High', 'High', 'High', 'Average', 'High',
       'High', 'High', 'High', 'Low', 'Low', 'High', 'High', 'Low',
       'High', 'High', 'Low', 'High', 'High', 'High', 'Low', 'Low',
       'High', 'High', 'High', 'High', 'High', 'High', 'Average', 'High',
       'High', 'High', 'High', 'High', 'High', 'High', 'Average', 'High',
       'Low', 'High', 'Average', 'High', 'Average', 'High', 'Average',
       'High', 'High', 'High', 'Average'], dtype='<U7')

In [22]:
y_test

array(['Average', 'High', 'Average', 'High', 'High', 'Average', 'High',
       'High', 'High', 'High', 'Average', 'Low', 'High', 'High', 'Low',
       'High', 'High', 'Low', 'High', 'High', 'High', 'Low', 'Low',
       'High', 'High', 'High', 'High', 'High', 'High', 'Average', 'High',
       'High', 'High', 'High', 'High', 'High', 'High', 'Average', 'High',
       'Low', 'High', 'Average', 'Low', 'Average', 'Average', 'Average',
       'High', 'High', 'High', 'Average'], dtype=object)

In [23]:
from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,y_pred)
score

0.92